### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#1]
Other than the unfortunate lack of ps4debug API to be able to implement console scans in your tool and make the scans faster, your tool works in several ways significantly better than the old cheater. Great job!!! :)

If you can kindly add the following features, they will certainly be very helpful for modders:
Undo the last scan, 
Add a column displaying the first scan result and be able to compare a scan with the first result (instead of the last one) if and when desired.
"Auto pause on scan" checkbox (it may be already available, but I couldn't find it in the query window).
Auto-refresh/Live Cheats (with configurable time interval)

Additionally - a light theme would be nice, if possible.

All these features are available in Cheat Engine's scanner and are very useful.

Thank you, Avan!

**Comment by avan06** [comment]
Hello,

Completed "Undo Last Scan" and "Scan Auto Pause" functions first, other features have not yet been determined

Thanks for the features suggestion

**Comment by Pharaoh2k** [comment]
Wow, thank you so much, buddy. :) 
There are few things I would like to discuss with you but can not post them in public.
How can we have direct communication? Got discord? Another messenger?

**Comment by Pharaoh2k** [comment]
Just to keep track of the improvements that we discussed in DM, as seen in Cheat Engine:
1) range:
allow 0x12345678-0x1000 to 0x12345678+0x2000
instead of writing explicitly in the field:
0x12344678 to 0x12347678

2) Multiple data view options in Hex view, if possible
b) configurable refresh rate interval for the hex view

3) Add "Not" option/checkbox to the scanner.
Add "Simple value" option/checkbox to the scanner.
Make the "exact" option more accurate.
Make the "exact" option the default option and make sure the selected option remains the same after scanning, as it seems to change by itself after scanning (for example, scanning with exact type sometimes auto-changes to fuzzy after scanning).

Thank you, Avan! :)

**Comment by avan06** [comment]
Hi Pharaoh2k,
Some existing features of Cheat Engine are added first in version [0.9.7.2-beta.](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.2-beta)

1. Hex editor: displaying decimal, float, and double
The hex value can be displayed as a numeric value, when the ByteGrouping of Hex editor is set to decimal or float or double.
Note: This feature is for display only and does not support direct editing of values.

2. Query window: format of range value supports offset
An offset can be used to enter the scan range in the Query window.

Thanks for the feature suggestion.

**Comment by Pharaoh2k** [comment]
This is great!! 
Any chance that we will be able to edit the values too?
Also, is there any way to search hex/AOB with wildcards, like in ps4 cheater?
For example: `80 3D ?? ?? ?? ?? 00` and `80 3D ** ** ** ** 00`
If not yet, can you please kindly add this?

Thank you, Avan!

**Comment by avan06** [comment]
Hi Pharaoh2k,
Some existing features of Cheat Engine are added first in version [0.9.7.3-beta.](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.3-beta)

Added [AutoPause, DoneResume, SimpleValue, Not] CheckBox in the query window
In addition, the AutoRefreshTimerInterval parameter is added in the options, and now the timer interval value of HexEditor refresh rate can be changed (in milliseconds)

___

It is currently not possible to edit the special display mode of the Hex editor.
search hex/AOB with wildcards, I can try to write and see in the next release.

Thanks for the feature suggestion.

**Comment by avan06** [comment]
Hi Pharaoh2k,


The following features have been added in [0.9.7.5-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.5-beta)
search hex/AOB with wildcards and Make the "exact" option more accurate

Thanks for the feature suggestion.

**Comment by Pharaoh2k** [comment]
Closing this issue, as I have already opened individual issues today for the remaining ones.
Thank you, Avan. :)
