### ISSUE TITLE
Possible bug: Flag Forward works in reverse way.

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#10]
Hi,

Silly bug that confuses a bit, the flag forward is not checked by default as you can see in the below capture:

![image](https://user-images.githubusercontent.com/9624829/201673183-d9d6504b-5664-4139-8831-6bb2ae201816.png)

Then when you press the button find with the flag forward by default unchecked the search direction is to forward in the page.

When you mark the flag  forward the search is reverse direction in the page.

Is this the correct way to work?  if not the possible options are:

1º Mark the flag forward by default and amend the code,

2º Rename forward by rearward, so then you don't have to change the code..

Note: There isn't any hurry to fix this bug, it can wait until a new release with new options.. ;)

**Comment by avan06** [comment]
Hi, JeymyAV

This issue has been fixed in [0.9.8.3-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.8.3-beta), now enable forward as find direction preset in Hex editor.

Thanks for helping to confirm the issue!

**Comment by JeymyAV** [comment]
It is solved, thank you..
