### ISSUE TITLE
[Hex Editor Issue] Error when you try to search a negative decimal value.

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#11]
We can find decimal values but when we try to find a negative value (decimal) the program raise the below value:

![image](https://user-images.githubusercontent.com/9624829/210222463-59d7d348-5302-4cea-93ff-9da1268d227f.png)

Is it possible to fix this issue? 

I know that as workaround we have the option to find negative value as hex value but you need to do the conversion before..

it will be better if you can fix this instead of doing manual conversions...

**Comment by avan06** [comment]
Hi, JeymyAV

Negative integer searches are now available in HexEditor.

[0.9.8.4-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.8.4-beta)

Thanks for the suggestion.

**Comment by JeymyAV** [comment]
Fixed.
