### ISSUE TITLE
[Hex Editor Issue] Searching the Hex value conversion from a decimal number no works on Hex Editor

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#12]
When on the Hex Editor we try to search a decimal value that is in memory it is found correctly. Example with the decimal value ‭498.322.808‬:
![image](https://user-images.githubusercontent.com/9624829/210227689-8288f28c-590a-47b4-910b-02a74165be20.png)

But when we try to find the same value but using his hex conversion 1D-B3-CD-78 it no works because the value cannot be found (cause in memory the hex value is stored in reverse order as you can see in the attached picture..

In the case that I put the hex value 78-CD-B3-1D this will be found but manually I have to change the order from little-endian to big-endian...
Independent the discussion about if application by default only do search with big endian number and not little endian numbers (or vise versa), it is a clear issue that the user can search and find the decimal value like ‭498.322.808‬ and if you made the conversion to his corresponding hex number that is ‭1DB3CD78‬ the tool is not able to find it. Example of conversion by Windows Calculator tool:

![image](https://user-images.githubusercontent.com/9624829/210228938-b2872035-2791-4860-9e68-a6350b006d2d.png)

Up to you how this issue/problem can be fixed but my personal suggestion or improvement is to put a new flag that said something like this:

Flag:    [] Search Big/Little Endian

When the flag is enabled search the hex value on both formats, when the flag is not enable only search in Little Endian (cause in Intel CPU is the default format)

Thank you Avan06

**Comment by b2ag** [comment]
Endianness is fix for PS4. High level hex representation for a decimal is also fix. When searching the memory by hex it is not obvious you want the bytes shifted around because what you actually want the search to do is an endianness  conversion before searching. Assuming I search 2 bytes and a short string like 0x39056C6565740A. How should the search know I need an endianness conversion only for the first two bytes but the rest should be left untouched?

**Comment by avan06** [comment]
Hi, JeymyAV

The support for LittleEndian endianness option in Hex search has been implemented in version [0.9.9.0-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.0-beta) of the Hex Editor window.

As mentioned by b2ag, it's challenging to determine how to support different mixed lengths (2 bytes, 4 bytes, 8 bytes, etc.) for LittleEndian conversion. 

Therefore, the current approach is to reverse the order of all input Hex values using Array.Reverse, regardless of the input's Hex length. This allows users to decide the Hex length they want to search for themselves. Thank you.

**Comment by JeymyAV** [comment]
In one word: PERFECT!!!! 👍 

Tested on version 0.9.9.3-beta
