### ISSUE TITLE
Status bar hiding last search results

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#15]
Hi, Avan, good to see you are back to work on the wonderful cheater neo! :)
There are multiple bugs to fix and feature requests.
I will start with this simple one and continue with the others a bit later:

![reGD8bj](https://github.com/avan06/PS4CheaterNeo/assets/5753365/b73276dc-3153-4e7d-a939-aeba2cd7933f)

**Comment by avan06** [comment]
Hi, Pharaoh2k,

I have fixed the issue where the status bar covers the last entry in the search results in version [0.9.9.1-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.1-beta). Thank you for reporting the error.

**Comment by Pharaoh2k** [comment]
Thank you, Avan. Closing this.
