### ISSUE TITLE
Very slow sections loading/refresh when there are many sections

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#16]
This issue was already reported and fixed in ps4 cheater, and hopefully can be fixed on neo as well.
On games with many sections, such as Cyberpunk 2077 (over 65,000 sections), the process attachment and loading/refresh time of the sections list is extremely slow.

**Comment by avan06** [comment]
Thank you for raising this issue. 
After testing with Cyberpunk 2077, it's clear that handling sections is indeed very slow. I've done my best to improve it in version [0.9.9.2-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.2-beta), but there will still be a delay of several seconds...

**Comment by Pharaoh2k** [comment]
Yes, **much much** better now. Great work!!! 
Thank you, avan!
Closing.
