### ISSUE TITLE
Feature request: Bulk adding of pointers

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#18]
Currently it's only possible to add 1 found pointer at a time to the cheat list. Please add a bulk feature.

**Comment by avan06** [comment]
Is the functionality shown in the image below what you are requesting?

Select multiple results and then right-click "Add to Cheat Grid."
![image](https://github.com/avan06/PS4CheaterNeo/assets/6281616/1b0aacbc-7aa9-4352-8e37-1b19bc73f079)

**Comment by Pharaoh2k** [comment]
Yeah, I think so, maybe I've missed it... I will test it to make sure. Closing this issue for now. Thanks.
