### ISSUE TITLE
Feature request: add a sections counter and a visible results counter

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#19]
Please kindly add:
total sections counter
selected sections counter 

and a visible search results counter (this one on the results bar:)
![reGD8bj](https://github.com/avan06/PS4CheaterNeo/assets/5753365/80967bec-3efb-4492-ad73-a14fcc8d4b14)

**Comment by avan06** [comment]
Hi, Pharaoh2k,

I have added the display of section-related count numbers in the Query window in version [0.9.9.1-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.1-beta).

In the Query window, the status bar now displays the total number of sections, the number of selected sections, and the memory size of the searched sections.
![query_section_count_1](assets/query_section_count_1.webp)
In the Query window, the status bar now displays the count of sections (found/selected/total) during the ScanTask process.
![query_section_count_2](assets/query_section_count_2.webp)

Thank you for the suggestion!

**Comment by Pharaoh2k** [comment]
Thanks.
Would be great if you can make the bar show up immediately when the Query window opens.
Right now it shows up only when selecting a section first.

**Comment by Pharaoh2k** [comment]
By the way, when I requested the section counts I actually meant something like this, I think it's a good location and implementation :)
![Nj8imuT](https://github.com/avan06/PS4CheaterNeo/assets/5753365/1acf5d68-a66b-42d4-a4b3-4a4a5ee99c55)

**Comment by avan06** [comment]
I have added the feature to display section-related counts immediately in version [0.9.9.2-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.2-beta).
I'm not considering displaying it below the SectionView for now, as that area is already quite compact.
Thank you.

**Comment by Pharaoh2k** [comment]
Understood. It seems to work perfectly fine. Thank you.
Would it be possible to also add a counter there for "Highlighted"?
