### ISSUE TITLE
[Request] A Better UI

### ISSUE THREAD

**Issue by Scalerize** [avan06/PS4CheaterNeo#2]
I Absolutely Love This Tool and I Know that a lot of LOVE was put into it, But I Think it's time for a Cleaner and Easier UI.

And Thank you for Keeping this tool up to date <3

**Comment by avan06** [comment]
Hi, do you have any suggestions on how to adjust the UI to achieve a cleaner and Easier UI? (eg what fields are not displayed or...)

Thank you

**Comment by Pharaoh2k** [comment]
UI improvements/corrections suggestions:

Add mouse hover tooltip/explanation to all the terms in all windows, including the Query window.

English terms in Option menus:
Remove all the "Enable". The checkboxes already say "Enable".
Enable Scan Done Resume -> Auto Resume

Remove the thousands separator in the port field (eg. 9,090 should show 9090).


Add UI color/backgrounds configurability for the sections list in the query window (different sizes have different colors).
Add a counter that shows how many sections are listed and how many are checked (as in PS4 Cheater).
Correct the Max: to be on one line in Query window
Change DoneResume to AutoResume and add space between AutoPause And AutoResume checkbox in Query window
Change the Slow to Slowdown and move it to the same line as AutoPause and AutoResume

**Comment by avan06** [comment]
Hi, Pharaoh2k

In 0.9.8.2-beta:

Remove the "Enable" beginning name of the checkbox option.
Change Done Resume to Auto Resume.
Moved Slow to the same line as AutoPause and AutoResume.

___
About the color of SectionView (sections list) in the query window, the previous version has already supported the setting.

- `QuerySectionViewFilterForeColor`:  
Determine the Query SectionView Filter foreground color.  
- `QuerySectionViewFilterBackColor`:  
Determine the Query SectionView Filter background color.  
- `QuerySectionViewFilterSizeForeColor`:  
Determine the Query SectionView FilterSize foreground color.  
- `QuerySectionViewFilterSizeBackColor`:  
Determine the Query SectionView FilterSize background color.  
- `QuerySectionViewExecutableForeColor`:  
Determine the Query SectionView executable foreground color.  
- `QuerySectionViewNoNameForeColor`:  
Determine the Query SectionView NoName foreground color.  
- `QuerySectionViewNoName2ForeColor`:  
Determine the Query SectionView NoName2 foreground color.  
- `QuerySectionViewItemCheck1BackColor`:  
Determine the Query SectionView ItemCheck1 background color.  
- `QuerySectionViewItemCheck2BackColor`:  
Determine the Query SectionView ItemCheck2 background color.

**Comment by Pharaoh2k** [comment]
![FvNVF4y](https://user-images.githubusercontent.com/5753365/202943069-4431265d-c0ab-49d7-8449-297a494c356c.png)
Adding summary of checked and unchecked sections  please.
