### ISSUE TITLE
Feature request: Improve the sections list selection

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#21]
At the moment it's only possible to select the section number column and then press spacebar to select/deselect in bulk.
![Ix8KtBm](https://github.com/avan06/PS4CheaterNeo/assets/5753365/2b7f039a-aaab-4022-a4c8-8680e9093822)

Please kindly improve it to be able to select the entire section rows, at any column clicked.
Also adding more features to the context menu can be helpful, such as:
- Select all marked
- Deselect all marked
- Invert selection
- Display only sections that contain _____ (for example lib)
etc.

This is an example from another ps4 scanner:

![nczJjyC](https://github.com/avan06/PS4CheaterNeo/assets/5753365/707877d2-0184-4ffb-b099-aeaa6150a48f)

**Comment by avan06** [comment]
Hi, Pharaoh2k,

I have added the suggested feature in version [0.9.9.1-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.1-beta). Thank you for the suggestion.

- Added support for FullRowSelect in the SectionView of the Query window.
This feature requires enabling `SectionViewFullRowSelect` in the Query of the Options window.
- Added support for "`Check All`", "`Uncheck All`", and "`Invert Checked`" in the right-click context menu of the SectionView in the Query window.

**Comment by Pharaoh2k** [comment]
This is great, thank you!
There is a huge performance hit when you try to do mass-section selection on games like cyberpunk. If you have a chance, please try that game.
Also, would be really great if you can add options (as in the screenshot above):
Un/Check all that contain _____
Un/Check all with protection _____

**Comment by avan06** [comment]
The "Un/Check all that contain" and "Un/Check all with protection" functions have been added in version [0.9.9.3-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.3-beta). Thank you for the feature suggestions!

Regarding the processing speed of mass-sections, there has been some initial improvement in version 0.9.9.2-beta. Currently, I can't think of any further improvements at this time.

**Comment by Pharaoh2k** [comment]
Great work, avan. Closing it for now. Might re-open in the future if needed.

**Comment by Pharaoh2k** [comment]
I have re-opened this issue to request adding a selection option for "Check/Uncheck all hidden sections" (to help with the new hidden section feature).

**Comment by avan06** [comment]
I have considered whether to add this feature, but later I thought that you can achieve the same functionality by entering "`Hidden`" in "`Un/Check that contains:`". 
Do you think this is okay, or is it still necessary to add "`Check/Uncheck all hidden`"?

**Comment by Pharaoh2k** [comment]
Yes, you're right, that's indeed an option and therefore not a high priority, but would be nice if you are ok to add it and it's not much work to do that. If you prefer not to add it, I'll just close this request.

**Comment by avan06** [comment]
The "Un/Check that contains Hidden" feature has been added in version [0.9.9.8-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.8-beta). Thank you.

**Comment by Pharaoh2k** [comment]
Works well. Thank you, avan. :)
Closing.
