### ISSUE TITLE
Feature request: Independent Hex Editor

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#26]
Sometimes we just want to use cheater neo for hex editing/viewing/browsing, but that requires to
- attach to the process
- load all sections
The problem is that in games with many sections like cyberpunk, this can take a while until we can actually use the Hex editor.
Could you please implement a way to be able to quickly attach to the process and Hex edit regardless of the small or large amount of sections?

**Comment by JeymyAV** [comment]
This can be resolved implementing the new feature Custom Sections:
[https://github.com/avan06/PS4CheaterNeo/issues/28](https://github.com/avan06/PS4CheaterNeo/issues/28)

**Comment by avan06** [comment]
In the current version, the section processing speed has been improved, so the Independent Hex Editor should no longer be a problem, right?

**Comment by avan06** [comment]
Work in progress... Added a Section switching ComboBox at the top right of the Hex Editor. Although attaching to the process is still required, switching Sections can now be done quickly.

![image](https://github.com/avan06/PS4CheaterNeo/assets/6281616/df3a0ba9-1e61-4db4-82df-c1fe0fb7a1bb)
![image](https://github.com/avan06/PS4CheaterNeo/assets/6281616/3d809211-d763-445a-bd10-57e02716ee20)

**Comment by Pharaoh2k** [comment]
Very nice, thank you, Avan. :)

**Comment by avan06** [comment]
The quick section switching feature has been implemented in version [0.9.9.8-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.8-beta). thank you.

**Comment by Pharaoh2k** [comment]
Seems to work perfectly. Thank you, Avan. Closing.
