### ISSUE TITLE
Feature request: Multiple entries for the option "Check that has Prot:"

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#29]
It is a great idea the new option "Check that has Prot:" but it only admit one entry right now.

Should be possible to put multiple entries because is very common to select the prot 3, 33 and 7.

So maybe you could allow something like this using a separator: 

3-7-33 and all the sections that match with this list of numbers should be selected.

**Comment by avan06** [comment]
Your suggestion is excellent, and I will add support for entering multiple protection values. I plan to use symbols such as ",", "-", ";", "|", and spaces to automatically split the protection conditions.

**Comment by JeymyAV** [comment]
Tested and works great!
