### ISSUE TITLE
Feature request: Make all the Texbox and Inputbox compatible with "Windows Calculator"

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#31]
This is a very weird, silly but annoying bug using Windows Calculator and PS4CheaterNeo. 

1º By example when I did some calculation on Windows Calculator and use the copy option:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/07e37a5a-3e16-4e83-84d9-b21a160a93f8)

2º I  paste this address in the Hex Editor:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/1f43aa7b-be55-47a7-b13b-78704ac02777)
3º The below error raise when I click in the button "OK":
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/fb557530-9879-43e1-8ea5-211e6166a939)

But if you paste the same in the Notepad everything is ok:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/1eb3aa7f-7e00-49da-8fd1-b1c26b5b1594)

But if you use a special editor you can see the special characters that windows calculator insert at the begin and at the end:

![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/c5a5d72e-9b2f-45b9-a97e-48155852cd6c)

So to fix it, you should be look up for any invalid characters and remove them when the user click in the ok button and before pass the value to others methods or instructions.. 

That's all!

**Comment by avan06** [comment]
This unusual issue is something I'm seeing for the first time. It seems like updating Windows might solve it. However, I can try automatically removing non-Hex characters as you suggested!

https://superuser.com/questions/1361155/how-to-stop-windows-10-calculator-from-enclosing-copied-text-in-202d-and-202c-un

**Comment by JeymyAV** [comment]
Yes, it is totally unusual but happen with different tools as you saw on my screenshot..
No, updating Windows 10 no resolved it (I have my windows up to date).
I think that this issue with Windows Calculator was resolved for Windows based in standard American, but for the international version of Windows they no fixed it... 

Anyway, tested your fix "prevention of entering non-Hex characters in [0.9.9.5-beta] and now works great!
