### ISSUE TITLE
Enhancement: Make input fields accept 0x prefix

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#36]
Perhaps the best solution is auto-stripping the 0x prefix rather than popping up an error when writing or pasting any value/address with 0x, or just accept it as is without errors.

**Comment by Pharaoh2k** [comment]
Hi Avan,
I think this is already done, right?

**Comment by avan06** [comment]
Hi Pharaoh2k,

This part may not be completed yet, and I'm actually not sure which input fields the proposed Enhancement refers to. Could you please provide additional context for clarification? Thank you.

**Comment by Pharaoh2k** [comment]
Honestly, I don't remember either, but everything seems to be working ok now, so I'll just close it and if I bump into it again, I'll reopen with more information. :)
