### ISSUE TITLE
Enhancement: Cheat grid window exit confirmation

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#39]
Please kindly add exit confirmation to the main window (cheat grid), such as:
Exit this window and terminate cheater neo?
YES/NO

**Comment by avan06** [comment]
In version [0.9.9.13-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.13-beta), a confirmation prompt has been added when closing the main window.

**Comment by Pharaoh2k** [comment]
Thank you, Avan
