### ISSUE TITLE
[Feature requests] Improve Hex Editor

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#4]
First, I love your work that you are doing with this tool to have better version of the old PS4Cheater. Simple Amazing and congratulations for it.
Of course there are a lot of things that can be improve but right now the most important issues that I have found is on the Hex Editor where is missing a good Inspector Data.

1º On the HexEditor, there is a zone that you call "Memory Info" that give us the offeset address and some conversion of the select byte and it shows asm code too. This is too much info, mixed, confused and incomplete. My suggestion is to remove the asm code info and put a data inspector like the below screen-short (selected byte is 7F value):, 
![image](https://user-images.githubusercontent.com/9624829/196399488-832b0cab-54be-4749-a0f4-1143f7809266.png)

a) As you can see in this picture, there are the most common conversions, and very quickly you are seeing the right conversion for the byte that you are selected.

b) Also, right now you are converting for one byte, but will be super, amazing, if you can do the same selecting 2, 3, 4, until 8 bytes continues bytes and do the corresponding conversion in the data inspector.

c) And the last, put in the data inspector a new checkbox called something like: 'Read in inverse order' ) so if this checkbox is marked and you select more than one byte, by example:  7F23,  you do the conversion for 237F that is mean reading the hex data in inverse order if the checkbox is marked, if not, then read as normal 7F23 and do the corresponding conversion.

2º Then, as my suggestion on point 1º is to remove the asm code info and put a button to open another window on top where you can put ALL the functionality about the asm code (reading, updating, etc). Even you can split the window space, half screen to see the bytes like now in the hexeditor, and half screen to see asm code (distribution horizontal (like now) or vertical distribution or a radio button to left the user to choose the distribution.

3º Anyway, you need to remove the asm code as is now because is not compatible with the refresh button. Because with the refresh button to 1 second or less (usually half second is the right choose) I have issues of performance because every second is disassembly the code and this doesn't have any sense or logic, because sometimes by example I am looking in a section with prot 3 or prot 1 that only can contains data and it never will contain asm code, so with the autorefresh enable and continuous disassembly  of this kind of section doesn't have any sense and it is doing issues on the tool.

I hope you can apply my suggestion as soon as you can specially 1- the data Inspector, that is very easy to apply...

Thank you, Avan!

**Comment by avan06** [comment]
Hi JeymyAV,

improved part of Hex Editor in [0.9.7.6-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.6-beta)

Thanks for the detailed improvement suggestions!

**Comment by JeymyAV** [comment]
Hi Avan06,

I have checked the changes that you have made and they are super! 👍 
Now the Hex Editor has better functionally...

For my own taste there are a few small improvements that I will think to implement if I were you, but they are totally optional and maybe for your point of view they aren't necessary to implement , but anyway, they are:

1º You put the conversion only for unsigned bytes, As you can see in my previous picture same byte can be different value in decimal when it is consider as signed.  Of course, maybe it no too usual to look up for signed bytes but it happen sometimes.

2º You did directly the conversion considering as reading on CPU mode (reading bytes in the inverse mode), and this is the correct way as I said previously. But sometimes can be interesting reading the bytes on memory mode (straight forward). 
Could be possible to put a radio button or something similar like this:
* Convert/Read bytes in CPU data/mode (default)
* Convert/Read bytes in memory data/mode
And then the user could change the conversion in real time if he need to do it.

3º You put the result of conversion and the corresponding value in hex. That is perfect, but for my own taste a small and cosmetic change but very useful is by example:

- Now: you display for a conversion value:  999999999 | 3B9AC9FF 
- option 1 could be:  999999999    |    3B 9A C9 FF  
- option 2 could be:  999999999    |    3B-9A-C9-FF  (this is my preferred one ) 

As I said previously, all these 3 changes are totally optional because as you did right now is enough, but if you can do them, for my own taste they will be amazing!

**Comment by avan06** [comment]
Hi JeymyAV,

improved Hex Editor in [0.9.7.7-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.7-beta)

Thanks for the new improvement suggestion~

**Comment by JeymyAV** [comment]
Great! you applied my last suggestions but unfortunately the tool now works me.

I opened a separate issue for that.

I hope that you can fix it soon so I can test again.

Thank you.

**Comment by JeymyAV** [comment]
I have been busy and until today I cannot tested the last improvements... 
In one word: 
                         Amazing!!!
