### ISSUE TITLE
Bug: error when bulk changing values

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#40]
In this example, I have scanned for float 1 in section 0 of the game Thief:
![Discord_2023-10-05_01-20-42](https://github.com/avan06/PS4CheaterNeo/assets/5753365/79af62fa-c7a7-418d-833d-b8d7194e8784)

Then I added all the values to the cheat grid, selected about 10% of them, and set the value to 0.1.
It starts changing some values, but then stops with this error:
![Discord_2023-10-05_01-21-58](https://github.com/avan06/PS4CheaterNeo/assets/5753365/7331d40e-476e-40fa-b396-1d3472414708)

This issue keeps happening over and over again and is easily reproducible.

**Comment by avan06** [comment]
In version [0.9.9.12-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.12-beta), some improvements have been made. When editing multiple row values, even if an error occurs, it will continue editing the next row, and the error message during the process will be displayed only after all edits are completed.

**Comment by avan06** [comment]
In version [0.9.9.13-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.13-beta), fixed the issue of encountering errors while editing multiple row values in Cheat window.

**Comment by Pharaoh2k** [comment]
Thank you, Avan
