### ISSUE TITLE
Hidden sections limits

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#42]
Hi Avan,
Currently, the last hidden section length default value is 0x40000000 and the max value is around 0x70000000
1) I noticed a bug that resets the number to zero if set higher than the max
2) I bumped into a game, Like A Dragon Gaiden The Man Who Erased His Name, that stores values at around 0x1300191fc8, while the highest memory I can map with the last hidden section option set to 0x70000000 is this:
![pxLsmgQ](https://github.com/avan06/PS4CheaterNeo/assets/5753365/8afecf7f-e2f1-4dd8-9f06-0c7d78013135)

As you can see, it's impossible to scan that 0x1300191fc8 memory area even with the hidden sections chunks added, also no way to browse/modify the hex memory there.
Could you please find a way to allow the scanning of hidden sections at much higher memory addresses like this one (0x1300191fc8) in cases like the above? Perhaps make the size limit of the last section much bigger and/or allow **custom** range scan and hex view/edit of much higher hidden sections?

**Comment by avan06** [comment]
Hi Pharaoh2k,

The data type for "Last Hidden Section Length" is ulong, theoretically, it can be set to a maximum of 0xFFFFFFFFFFFFFFFF. Could you try setting this value to approximately 400000000 (just larger than 0x1300191fc8 - 0xfe0300000 = 0x31FE91FC8)?

Thank you.

**Comment by Pharaoh2k** [comment]
As you can see in this video, it doesn't allow me to change it to 400000000
[https://www.youtube.com/watch?v=tVi58GHXEvw]

**Comment by avan06** [comment]
Thank you to Pharaoh2k for creating a video explaining this issue. Upon investigation, it appears to be a limitation with the .Net NumericUpDown component when the Hexadecimal property is set to true:

[When the Hexadecimal property is set to true, the Maximum property should be set to Int32.MaxValue, and the Minimum property should be set to Int32.MinValue.](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.numericupdown.hexadecimal?view=windowsdesktop-8.0#remarks)

I haven't figured out an improvement yet...

**Comment by Pharaoh2k** [comment]
Bummer.
Is it possible to disable the hexadecimal property and use the decimal property instead with the Ulong, then do the hex math conversion afterwards, to workaround that limit?

**Comment by avan06** [comment]
The issue has been resolved in version  [1.0.1.4](https://github.com/avan06/PS4CheaterNeo/releases/tag/1.0.1.4). 

 Please assist in testing with the new version. Thank you.

**Comment by Pharaoh2k** [comment]
Works perfectly fine now. Thank you, Avan.
