### ISSUE TITLE
Grammer: "New settings have been saved" instead of "save"

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#44]
When settings are saved, a popup window "save" is displayed.
I suggest changing it to something such as "New settings have been saved".

**Comment by avan06** [comment]
Implemented this suggestion in version [1.0.1.3](https://github.com/avan06/PS4CheaterNeo/releases/tag/1.0.1.3). Thank you for the suggestion.

Additionally, I have added a feature to display the list of modified options. 
This feature can be enabled or disabled through the `DisplayChangesListWhenSaving` in the option window, and it is enabled by default.
![image](https://github.com/avan06/PS4CheaterNeo/assets/6281616/8618efc2-81de-4cd4-ae7c-4bd455be5427)
