### ISSUE TITLE
Bug in Hexviewer

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#47]
Hi, Avan

I think there is a bug in the Hex viewer.
Here is an example, I have set the view to Float and expected to see 0.5, but I am getting this:
![xhldJi9](https://github.com/avan06/PS4CheaterNeo/assets/5753365/5af7b114-dc20-4b11-8c8c-aecd77c7c7db)
![QfR0UeM](https://github.com/avan06/PS4CheaterNeo/assets/5753365/eddf24bb-fa09-45bf-aa6a-b0023adcca12)

**Comment by Pharaoh2k** [comment]
And this is how that memory section looks in Cheat Engine Hex viewer on float mode:

![yOjYCSw](https://github.com/avan06/PS4CheaterNeo/assets/5753365/61bb62e4-b40e-427c-9a91-f77657d93fc4)

**Comment by avan06** [comment]
In version [1.0.2.9](https://github.com/avan06/PS4CheaterNeo/releases/tag/1.0.2.9), the floating-point number display format has been improved. Thank you for testing and providing feedback!

**Comment by Pharaoh2k** [comment]
Well done. Thank you! :)
