### ISSUE TITLE
New option UIOpacity raise a .net error and close the app.

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#5]
Hi,

The last 0.9.7.7-beta no works, because the new option UIOpacity  raise a .net error:
![image](https://user-images.githubusercontent.com/9624829/199717248-e8933177-fa52-461a-b618-33759098705a.png)

Below my .Net configuration to help you to fix the issue:

<32Bit>
2.0.50727.9164
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.8.4515.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.9164
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.8.4515.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

==== Installed .NET Frameworks ====
.NET FW 2.0 SP 2 (CLR 2.0)
.NET FW 3.0 SP 2 (CLR 2.0)
.NET FW 3.5 SP 1 (CLR 2.0)
.NET FW 4.6.2 Windows 10 May 2020 Update(CLR 4.0)
.NET FW 4.7 Windows 10 May 2020 Update(CLR 4.0)
.NET FW 4.7.1 Windows 10 May 2020 Update(CLR 4.0)
.NET FW 4.7.2 Windows 10 May 2020 Update(CLR 4.0)
.NET FW 4.8 Windows 10 May 2020 Update(CLR 4.0)

==== Languages ====
< Installed Languages 3.0>
English - United States
< Installed Languages 3.5.x>
English - United States
< Installed Languages 4.x>
English - United States

==== Updates ====
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217

If you need more info don't hesitate to ask me...

**Comment by JeymyAV** [comment]
Yes, I can see these folders and his files and open and see similar structure like you screenshot but only for version 0.9.7.5 and other for 0.9.7.6.

There isn't any folder and his corresponding user.config for the new version 0.9.7.7. 

Maybe you change something and the folder and file is not created automatically and for you is working because you already have it installed on your pc...

**Comment by avan06** [comment]
I tested here, even if I delete "...\0.9.7.7\user.config" and execute PS4CheaterNeo again, it will automatically generate "0.9.7.7\user.config"

I just released a new version, maybe you can also try 0.9.7.8-beta to see if the error still occurs

**Comment by JeymyAV** [comment]
Most better but no works at all..

With 0.9.7.8-beta the app raise to sequential errors in a window that I have to accept but this time the app start and the folders have been created. Below both errors: 
- First error:
![image](https://user-images.githubusercontent.com/9624829/199752600-44e94ed1-1453-42f5-bacc-f647bfb50169.png)

- Second Error:
![image](https://user-images.githubusercontent.com/9624829/199752665-2a4741db-c6f9-41f0-a999-8e569d23be9e.png)

this user.config file seems correct:
![image](https://user-images.githubusercontent.com/9624829/199753718-bf27c139-a8f3-449a-b81c-4fbbf2d5b39f.png)


Now every time that I am starting the app, it raise these 2 errors...  

I think that I know which is the problem by the screenshot message error. 
I think that is the typical language regional error on the character that separate the integer part of the decimal part.

**Comment by avan06** [comment]
Well, maybe there is something wrong with the .Net environment, 
please execute the Microsoft .NET Framework Repair Tool and try to repair the .NET Framework

Microsoft .NET Framework Repair Tool
https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by JeymyAV** [comment]
I have good news, I know exactly what it is happening and how you can fix it.

**- The root of the issue:**
First, I have ran .NET Framework Repair Tool following your advice but the tool don't detected anything wrong with my .net installation and even after that I have updated my windows 10 to the new update 22h2 that have been relapsed a few days ago. This actualization has some fixed for the .net framework 4.8 and I was hoping that this will fix this weird issue.
After update, I ran again app and the same 2 errors. So here, I decided do a break-point and come back to error, read again the message, and for me was very clear, the problem is the regional configuration of the windows/user.

So I open on windows settings the regional configuration and change all the formats, dates, etc to US configuration, apply the changes and ran again the app, and EUREKA!!!, the application start without error.
Then,  Then,  I have revert again to my regional configuration, start again the app and again the same errors as expected.

I have explained all my steps in detail because if you want see it for yourself you can reproduced the error before fixing it.

**The conclusion**: 
 This error will be happen a any user with the language/regional configuration different that US, by example, European regional variants,  Asian regional variants, African regional variants, etc...

I think that you don't have intention to make an international app with support all the regional configuration of the world because can be a nightmare tasks for one person.  :)

**The easy solution:**
After googling for a workaround I have found some answers on Microsoft site and others sites and  below this is my proposal code to merge with your existing one :

	public void ApplyUI()
        {
            try
            {

                // Creates and initializes a CultureInfo.
                CultureInfo myCI = new CultureInfo("en-US", false);

                // Clones myCI and modifies the DTFI and NFI instances associated with the clone.
                CultureInfo myCIclone = (CultureInfo)myCI.Clone();
                myCIclone.DateTimeFormat.AMDesignator = "a.m.";
                myCIclone.DateTimeFormat.DateSeparator = "-";
                myCIclone.NumberFormat.CurrencySymbol = "USD";
                myCIclone.NumberFormat.NumberDecimalDigits = 4;
                myCIclone.NumberFormat.NumberDecimalSeparator = ".";
                myCIclone.NumberFormat.CurrencyDecimalSeparator = ".";
                myCIclone.NumberFormat.NumberGroupSeparator = ",";

                Thread.CurrentThread.CurrentCulture = myCIclone;

                Opacity = Properties.Settings.Default.UIOpacity.Value;
				cheatGridViewRowIndexForeBrush = new SolidBrush(Properties.Settings.Default.MainCheatGridViewRowIndexForeColor.Value); //SystemBrushes.HighlightText

I am sure 100% that this code will fix the error no only for my case, if for any user with any regional configuration different to US.

**Comment by avan06** [comment]
> **The conclusion**:
> This error will be happen a any user with the language/regional configuration different that US, by example, European regional variants, Asian regional variants, African regional variants, etc...

JeymyAV you are so amazing, I never thought that Culture Info would cause the float conversion failure!

I will fix this issue as soon as you suggest, thank you.

**Comment by avan06** [comment]
I have fixed this issue in [0.9.7.9-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.9-beta)

Change the current thread's Culture to CultureInfo.InvariantCulture (that is culture-independent (invariant)).

Avoid the case where CurrentCulture.NumberFormatInfo.NumberDecimalSeparator is not "."

Thank you JeymyAV for assisting with testing.

**Comment by JeymyAV** [comment]
Finally [0.9.7.9-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.7.9-beta) works!!!

Now I can continue testing the app...
