### ISSUE TITLE
mscorlib error

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#6]
Hi, Avan

I am getting this error on CUSA04607 v1.02 when trying to load all the processes and when trying to search for pointer:
![sb8hpPO](https://user-images.githubusercontent.com/5753365/200163885-f9f4473a-a504-4c59-8474-44510f2d1496.png)

To reproduce, load the game and start playing, connect with PS4CheaterNeo, try to open query window, if it doesn't error, try to disable sections filter

I tried older builds of PS4CheaterNeo and got the same problem.

**Comment by avan06** [comment]
Hi, Pharaoh2k

This issue could trigger when the Section reaches thousands or more, now fixed in [0.9.8.0-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.8.0-beta).

Thanks for reporting bugs

**Comment by Pharaoh2k** [comment]
Thank you so much for such a quick fix. You are incredible, buddy.
Will test and close the issue if it's fully fixed. Will report if not. :)

**Comment by Pharaoh2k** [comment]
Seem to work well. Thanks again! :)
