### ISSUE TITLE
Error when change the page on the HexEditor

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#9]
Hi, 
I think there is a bug in the Hex Editor with the last beta 0.9.8.1. To reproduce: 

1º I have open Hex Editor from the main from and using button on the toolbar.

2º I have put any address like this 0216340D30 and you can see in the below picture everything is shown ok:

![image](https://user-images.githubusercontent.com/9624829/201540590-f4f5d705-2838-4cbd-997f-9ddf67f18b05.png)

3º But when you want change the page (pressing the previous button or next button or by selecting any page from the list of page) everything is 0:

![image](https://user-images.githubusercontent.com/9624829/201540759-c85da495-020d-4f2a-b01b-7e9d946745ae.png)

Even if you come back to original on the step 2, now it only contains zeros..

**Comment by avan06** [comment]
Hi, JeymyAV

Do you have to restart the game?
I found that this happens when the game is restarted,
because the pid changes due to restarting the game, which will cause the correct memory data to not be obtained.

If this is the case, I can improve it.

**Comment by JeymyAV** [comment]
You are right, I have retested again and it is working well...

It have been my mistake because there is another bug (I think a silly bug) when using the Find button to search the values in the page, the flag forward is working in reverse way, so I have don't see the expected values to change the page and see only zeros...

So, I'm going to close it and open other issue with this easy bug with this flag forward.
